title: 'Grapevine Network Management'
default_lang: en
author:
  name: 'Nigel Frost'
  email: nigel.frost@gvnm.co.uk
taxonomies:
  - category
  - tag
metadata:
  description: 'IT Support Made Easy'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
